[package]
name = "binderdump"
version = "0.1.0"
edition = "2021"

[lib]
name = "binderdump"
path = "src/lib.rs"

[[bin]]
name = "binderdump"
path = "src/bin.rs"

[dependencies]
env_logger = "0.11.3"
log = "0.4.21"
