[package]
name = "binderdump"
version = "0.1.0"
edition = "2021"

[lib]
name = "binderdump"
path = "src/lib.rs"

[[bin]]
name = "binderdump"
path = "src/bin.rs"

[dependencies]
anyhow = "1.0.85"
env_logger = "0.11.3"
libc = "0.2.155"
log = "0.4.21"
nix = "0.28.0"

[target.'cfg(not(target_os = "android"))'.dependencies]
libbpf-rs = { version = "0.22.1" }

[target.'cfg(target_os = "android")'.dependencies]
libbpf-rs = { version = "0.22.1", features = ["static"] }
android_logger = "0.13"

[build-dependencies]
libbpf-cargo = "0.23.1"
