cargo-features = ["per-package-target"]
[workspace]

members = [
    "binderdump",
    "binderdump-sys",
    "binderdump-structs",
    "binderdump-dissector",
    "binderdump-derive",
    "binderdump-epan-sys", "binderdump-trait",
]

resolver = "2"
