#!/bin/bash
# Regenerate binderdump-dissector/tests/fixtures/bundle.pcapng — a small capture
# exercising Bundle decode on a real binder transaction generated by the framework.
#
# It drives IApplicationThread.setCoreSettings(in Bundle coreSettings) — a method
# with Bundle as its only parameter. system_server sends this to every running
# Java process whenever certain system settings change.
#
# Trigger: toggle Settings.Global.DEBUG_VIEW_ATTRIBUTES (0→1→0). Each change
# causes system_server to rebuild the core settings Bundle from live system
# values (widget timing, font metrics, debug flags, etc.) and broadcast it
# to all running apps via their IApplicationThread binder.
#
# Why this interface:
#   - Only parameter is Bundle — nothing before it can block decode.
#   - system_server is the sender: real framework Java, not a hand-crafted parcel.
#   - Reliably triggerable from adb without an installed APK.
#
# The captured frame is filtered to the first setCoreSettings call so the
# fixture stays small.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
FIXTURE="${SCRIPT_DIR}/fixtures/bundle.pcapng"
CORPUS_DIR="${REPO_ROOT}/binderdump-aidl/data/aosp"

adb root >/dev/null 2>&1 || true
adb wait-for-device
adb shell rm -f /data/local/tmp/out.pcapng

OUT_DIR="$(mktemp -d -t binderdump-bfix.XXXXXX)"
trap 'rm -rf "$OUT_DIR"' EXIT
export OUT_DIR
LOG="${OUT_DIR}/cap.log"

(cd "$REPO_ROOT" && cargo run --release --bin binderdump -p binderdump -- -t 8 >"$LOG" 2>&1) &
CAPTURE_PID=$!
# wait until the binary is actually capturing before driving traffic
for _ in $(seq 1 40); do grep -q 'capturing events' "$LOG" && break; sleep 0.3; done

# Toggle debug_view_attributes to trigger system_server to rebuild and send
# the core-settings Bundle to all running Java processes.
adb shell '
  settings put global debug_view_attributes 1
  sleep 0.3
  settings put global debug_view_attributes 0
  sleep 0.3
  settings put global debug_view_attributes 1
  sleep 0.3
  settings put global debug_view_attributes 0
'

wait "$CAPTURE_PID"

adb pull /data/local/tmp/out.pcapng "${OUT_DIR}/out.pcapng"

# Find the first setCoreSettings frame (transaction code 29 on android.app.IApplicationThread).
# Use the corpus-aware dissector to match by method name.
FIRST_FRAME=$(tshark -r "${OUT_DIR}/out.pcapng" \
  -o "binderdump.aosp_corpus_dir:${CORPUS_DIR}" \
  -T fields -e frame.number \
  -Y 'binderdump.ioctl_data.bwr.transaction.method_name=="setCoreSettings"' \
  2>/dev/null | head -1)

if [ -z "$FIRST_FRAME" ]; then
  echo "ERROR: no setCoreSettings frames found." >&2
  echo "  Check the device has running Java processes and debug_view_attributes can be toggled." >&2
  exit 1
fi

tshark -r "${OUT_DIR}/out.pcapng" \
  -Y "frame.number==${FIRST_FRAME}" \
  -w "$FIXTURE"
ls -la "$FIXTURE"
