cargo-features = ["per-package-target"]

[package]
name = "bindump-epan-sys"
version = "0.1.0"
edition = "2021"
links = "wireshark"
forced-target = "x86_64-unknown-linux-gnu"

[dependencies]


[build-dependencies]
bindgen = "0.69.4"
pkg-config = "0.3.30"
