[package]
name = "binderdump-dissector"
version = "0.1.0"
edition = "2021"
links = "wireshark"

[lib]
crate-type = ["cdylib"]

[dependencies]
binderdump-structs = { path = "../binderdump-structs" }
bitmask = "0.5.0"
lazy_static = "1.4.0"

[build-dependencies]
bindgen = "0.69.4"
pkg-config = "0.3.30"
